/* eslint-disable no-unused-vars */
export enum RegistrationStatus {
  AWAITING_EMAIL_VERIFICATION,
  USER_ALREADY_EXISTS,
  INVALID_TOKEN,
  EMAIL_ALREADY_VERIFIED,
  EMAIL_VERIFICATION_EXPIRED,
  FAILURE,
  SUCCESS,
}
