apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "sparrow.fullname" . }}-api-deployment
  namespace: sparrow-{{ .Values.environment.name }}
  labels:
    app: {{ template "sparrow.fullname" . }}
    chart: {{ template "sparrow.chart" . }}
    component: "{{ .Values.api.fullname }}"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  selector:
    matchLabels:
      app: {{ template "sparrow.fullname" . }}
      component: "{{ .Values.api.name }}"
      release: {{ .Release.Name }}
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ template "sparrow.fullname" . }}
        component: "{{ .Values.api.name }}"
        release: {{ .Release.Name }}
    spec:
      securityContext:
        runAsUser: 1000
      containers:
      - name: {{ template "sparrow.fullname" . }}-api
        image: "{{ .Values.api.image.repository }}:{{ .Values.api.image.tag }}"
        imagePullPolicy: "{{ .Values.api.image.pullPolicy }}"
        env:
          - name: NODE_ENV
            valueFrom:
              secretKeyRef:
                name: sparrow-node-env
                key: NODE_ENV
          - name: SESSION_SECRET
            valueFrom:
              secretKeyRef:
                name: sparrow-session-secret
                key: SESSION_SECRET
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: sparrow-database-url
                key: DATABASE_URL
          - name: PORT
            valueFrom:
              secretKeyRef:
                name: sparrow-port
                key: PORT
          - name: FRONT_END_URL
            valueFrom:
              secretKeyRef:
                name: sparrow-frontend-url
                key: FRONT_END_URL
          - name: EMAIL_USER
            valueFrom:
              secretKeyRef:
                name: sparrow-email-user
                key: EMAIL_USER
          - name: EMAIL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: sparrow-email-password
                key: EMAIL_PASSWORD
          - name: GOOGLE_CLIENT_ID
            valueFrom:
              secretKeyRef:
                name: sparrow-google-client-id
                key: GOOGLE_CLIENT_ID
          - name: GOOGLE_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: sparrow-google-client-secret
                key: GOOGLE_CLIENT_SECRET
          - name: GOOGLE_CALLBACK_URL
            valueFrom:
              secretKeyRef:
                name: sparrow-google-callback-url
                key: GOOGLE_CALLBACK_URL
        ports:
        - containerPort: 3000
        resources: {}
        livenessProbe:
          httpGet:
            port: 3000
            path: /
          initialDelaySeconds: 3
          periodSeconds: 3
      restartPolicy: Always
status: {}
