apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: split-{{ .Values.environment.name }}-ingress
  namespace: split-{{ .Values.environment.name }}
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  ingressClassName: nginx
  tls:
    - hosts:
      - {{ .Values.environment.hostPrefix }}split.direct
      - api.{{ .Values.environment.hostPrefix }}split.direct
      secretName: split-tls-{{ .Values.environment.name }}
  rules:
    - host: api.{{ .Values.environment.hostPrefix }}split.direct
      http:
        paths:
          - backend:
              service:
                name: {{ .Values.applicationName }}-micro-users-service
                port:
                  number: {{ .Values.microUsers.port }}
            path: /users/?(.*)
            pathType: ImplementationSpecific
          - backend:
              service:
                name: split-direct-micro-properties-service
                port:
                  number: {{ .Values.microProperties.port }}
            path: /properties/?(.*)
            pathType: ImplementationSpecific
          - backend:
              service:
                name: split-direct-micro-expenses-service
                port:
                  number: {{ .Values.microExpenses.port }}
            path: /expenses/?(.*)
            pathType: ImplementationSpecific
    - host: {{ .Values.environment.hostPrefix }}split.direct
      http:
        paths:
          - path: /?(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ .Values.applicationName }}-ui-service
                port:
                  number: {{ .Values.ui.port }}
