apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sparrow-{{ .Values.environment.name }}-ingress
  namespace: sparrow-{{ .Values.environment.name }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  tls:
    - hosts:
      - {{ .Values.environment.hostPrefix }}split.direct
      secretName: sparrow-tls-{{ .Values.environment.name }}
  rules:
    - host: api.{{ .Values.environment.hostPrefix }}split.direct
      http:
        paths:
          - backend:
              service:
                name: {{ .Values.applicationName }}-api-service
                port:
                  number: 3000
            pathType: Prefix
            path: /
    - host: {{ .Values.environment.hostPrefix }}split.direct
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.applicationName }}-ui-service
                port:
                  number: 80
