apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.applicationName }}-ui-service
  namespace: split-{{ .Values.environment.name }}
  labels:
    app: {{ .Values.applicationName }}
    chart: {{ template "split.chart" . }}
    component: "{{ .Values.ui.name }}"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  ports:
    - name: http
      port: 4000
      targetPort: 4000
  selector:
    app: {{ template "split.fullname" . }}
    component: "{{ .Values.ui.name }}"
    release: {{ .Release.Name }}
