apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "split.fullname" . }}-micro-expenses-deployment
  namespace: split-{{ .Values.environment.name }}
  labels:
    app: {{ template "split.fullname" . }}
    chart: {{ template "split.chart" . }}
    component: "{{ .Values.microExpenses.name }}"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    date: "{{ now | unixEpoch }}"
spec:
  selector:
    matchLabels:
      app: {{ template "split.fullname" . }}
      component: "{{ .Values.microExpenses.name }}"
      release: {{ .Release.Name }}
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: {{ template "split.fullname" . }}
        component: "{{ .Values.microExpenses.name }}"
        release: {{ .Release.Name }}
    spec:
      securityContext:
        runAsUser: 1000
      containers:
        - name: {{ template "split.fullname" . }}-api
          image: "{{ .Values.microExpenses.image.repository }}:{{ .Values.microExpenses.image.tag }}"
          imagePullPolicy: "{{ .Values.microExpenses.image.pullPolicy }}"
          env:
            - name: NODE_ENV
              valueFrom:
                secretKeyRef:
                  name: split-node-env
                  key: NODE_ENV
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: split-micro-expenses-database-url
                  key: DATABASE_URL
            - name: PORT
              valueFrom:
                secretKeyRef:
                  name: split-micro-properties-port
                  key: PORT
            - name: FRONT_END_URL
              valueFrom:
                secretKeyRef:
                  name: split-frontend-url
                  key: FRONT_END_URL
            - name: EMAIL_USER
              valueFrom:
                secretKeyRef:
                  name: split-email-user
                  key: EMAIL_USER
            - name: EMAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: split-email-password
                  key: EMAIL_PASSWORD
            - name: GOOGLE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: split-google-client-id
                  key: GOOGLE_CLIENT_ID
            - name: GOOGLE_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: split-google-client-secret
                  key: GOOGLE_CLIENT_SECRET
            - name: GOOGLE_CALLBACK_URL
              valueFrom:
                secretKeyRef:
                  name: split-google-callback-url
                  key: GOOGLE_CALLBACK_URL
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: split-micro-jwt-secret
                  key: JWT_SECRET
            - name: DATADOG_API_KEY
              valueFrom:
                secretKeyRef:
                  name: split-datadog-api-key
                  key: DATADOG_API_KEY
          ports:
            - containerPort: {{ .Values.microExpenses.port }}
          resources: {}
          livenessProbe:
            httpGet:
              port: {{ .Values.microExpenses.port }}
              path: /
            initialDelaySeconds: 3
            periodSeconds: 3
      restartPolicy: Always
status: {}
