applicationName: split-direct
replicaCount: 1

environment:
  name: production
  hostPrefix:

ui:
  name: ui
  image:
    repository: jonathanleedev/split-direct-ui
    tag: latest
    pullPolicy: Always
  port: 80

api:
  name: api
  image:
    repository: jonathanleedev/split-direct-api
    tag: latest
    pullPolicy: Always
  port: 3000

microUsers:
  name: micro-users
  image:
    repository: jonathanleedev/split-micro-users
    tag: 0.2.11
    pullPolicy: Always
  port: 3001
