applicationName: split-direct
replicaCount: 1
environment:
  name: production
  hostPrefix: null
rabbitmq:
  namespace: split-production
  replicas: 3
ui:
  name: ui
  image:
    repository: jonathanleedev/split-ui
    tag: 0.2.74
    pullPolicy: Always
  port: 4000
microUsers:
  name: micro-users
  image:
    repository: jonathanleedev/split-micro-users
    tag: 0.2.74
    pullPolicy: Always
  port: 3000
microProperties:
  name: micro-properties
  image:
    repository: jonathanleedev/split-micro-properties
    tag: 0.2.74
    pullPolicy: Always
  port: 3000
microExpenses:
  name: micro-expenses
  image:
    repository: jonathanleedev/split-micro-expenses
    tag: 0.2.74
    pullPolicy: Always
  port: 3000
microMail:
  name: micro-mail
  image:
    repository: jonathanleedev/split-micro-mail
    tag: 0.2.74
    pullPolicy: Always
  port: 3000
