applicationName: split-direct
replicaCount: 1
environment:
  name: production
  hostPrefix: null
ui:
  name: ui
  image:
    repository: jonathanleedev/split-ui
    tag: 0.2.28
    pullPolicy: Always
  port: 4000
api:
  name: api
  image:
    repository: jonathanleedev/split-api
    tag: 0.2.28
    pullPolicy: Always
  port: 3000
microUsers:
  name: micro-users
  image:
    repository: jonathanleedev/split-micro-users
    tag: 0.2.28
    pullPolicy: Always
  port: 3001
