applicationName: sparrow-express
replicaCount: 1

environment:
  name: staging
  hostPrefix: staging.

ui:
  name: ui
  image:
    repository: jonathanleedev/sparrow-express-ui
    tag: stage-0.2.25
    pullPolicy: Always
  port: 80

api:
  name: api
  image:
    repository: jonathanleedev/sparrow-express-api
    tag: 0.2.25
    pullPolicy: Always
  port: 3000
