applicationName: split
replicaCount: 1

environment:
  name: staging
  hostPrefix: staging.

ui:
  name: ui
  image:
    repository: jonathanleedev/split-ui
    tag: stage-0.1.0
    pullPolicy: Always
  port: 80

api:
  name: api
  image:
    repository: jonathanleedev/split-api
    tag: 0.1.0
    pullPolicy: Always
  port: 3000
