import {MAX_PROPERTY_NAME_LENGTH, MIN_PROPERTY_NAME_LENGTH} from './property';

export const MIN_EXPENSE_NAME_LENGTH = MIN_PROPERTY_NAME_LENGTH;
export const MAX_EXPENSE_NAME_LENGTH = MAX_PROPERTY_NAME_LENGTH;
export const DEFAULT_CURRENCY_CODE_LENGTH = 3;
