export const DEFAULT_TOKEN_BUFFER_ENCODING: BufferEncoding = 'hex';
export const DEFAULT_TOKEN_SIZE = 64;
export const DEFAULT_TOKEN_EXPIRY_TIME_MINUTES = 15;

export const DEFAULT_TOKEN_EXPIRY_TIME_DAYS = 15;

export const DEFAULT_TOKEN_HOLD_EXPIRY_TIME_MINUTES = 1;
