name: '[STAGE-UI] Docker Image Build & Push (SSR)'

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:

  build:

    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get Package Version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@v1.3.1
        with:
          path: services/split-ui
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: "{{defaultContext}}:./ui/split-ui/"
          file: ./Dockerfile-stage
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/split-ui:stage-${{ steps.package-version.outputs.current-version}}
