name: Deploy to Staging

on:
  push:
    branches: [main]

jobs:
  deployment:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Helm Deploy
        uses: vimeda/helm@v1.7.0
        with:
          namespace: default
          release: split-direct-staging
          chart: deployment
          value-files: 'deployment/values/staging-values.yaml'
        env:
          KUBECONFIG_FILE: ${{ secrets.KUBECONFIG }}
