name: 'Docker Image Build & Push'

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:

  build-micro-users:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        node-version: [20.x]
    name: Lerna Build using Node v${{ matrix.node-version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: yarn
          cache-dependency-path: '**/yarn.lock'
      - run: yarn install
      - run: yarn lerna run build
        env:
          CI: true
      - name: Get Package Version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@v1.3.1
        with:
          path: services/split-micro-users
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          file: ./Dockerfile-split-micro-users
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/split-micro-users:${{ steps.package-version.outputs.current-version}}
