name: SonarCloud Analysis

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions:
  pull-requests: read

jobs:
  analysis:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: yarn
          cache-dependency-path: '**/yarn.lock'
      - name: Install Dependencies
        run: yarn install
      - name: Build Packages and Services
        run: yarn lerna run build
      - name: Run Tests
        run: yarn lerna run test
      - name: Aggregate Coverage
        run: ./coverage.sh
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args:
            -Dsonar.projectKey=jonathan-lee-devel_split
            -Dsonar.organization=jonathan-lee-devel
            -Dsonar.sources=packages/split-auth,packages/split-constants,packages/split-observability,services/split-micro-users/src,services/split-micro-properties/src,services/split-micro-expenses/src
            -Dsonar.tests=services/split-micro-users/src,services/split-micro-properties/src,services/split-micro-expenses/src
            -Dsonar.inclusions=**
            -Dsonar.exclusions=**/*.spec.ts,**/index.ts,**/src/app.ts,**/src/routes.ts,**/src/server.ts,**/src/middleware/request-middleware.ts,**/src/logger.ts,**/src/lib/**.ts,**/src/models/**/**.ts
            -Dsonar.test.inclusions=src/**/*.spec.ts,src/**/*.spec.tsx,src/**/*.test.ts,src/**/*.test.tsx
            -Dsonar.javascript.lcov.reportPaths=coverage/lcov/lcov.info
