name: '[UI] Node.js CI'

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: 'services/ui-ssr'

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: yarn
        cache-dependency-path: '**/yarn.lock'
    - run: yarn install
    - run: yarn run build:prod
